server:
  port: 18080

spring:
  profiles:
    active: ${ACTIVE:dev}
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  type-aliases-package: com.tencent.wxcloudrun.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
